// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyEmotionWithGateway(arg1:main.EmotionTextRequest):Promise<main.TextReviewResult>;

export function AutoTranscribeReference(arg1:main.ReferenceTranscriptRequest):Promise<string>;

export function Bootstrap():Promise<main.StudioBootstrap>;

export function CheckWorker(arg1:main.WorkerSession):Promise<main.WorkerHealth>;

export function CreateVoice(arg1:main.VoiceCreateRequest):Promise<main.VoiceProfile>;

export function DeleteHistory(arg1:string):Promise<Array<main.GenerationHistory>>;

export function DeleteVoice(arg1:main.WorkerSession,arg2:string):Promise<Array<main.VoiceProfile>>;

export function GenerateVoice(arg1:main.GenerateRequest):Promise<main.GenerationResult>;

export function ImportGoogleDriveDocument(arg1:string):Promise<main.ImportedDocument>;

export function ImportTextDocument(arg1:string):Promise<main.ImportedDocument>;

export function ListGatewayModels(arg1:main.GatewayModelsRequest):Promise<Array<main.GatewayModel>>;

export function OpenColabNotebook():Promise<void>;

export function OpenGoogleDrive():Promise<void>;

export function OpenHistoryAudio(arg1:string):Promise<void>;

export function PreviewVoice(arg1:main.GenerateRequest):Promise<main.GenerationResult>;

export function ReadReferenceAudioSource(arg1:string):Promise<string>;

export function ReadVoiceReferenceAudio(arg1:string):Promise<string>;

export function RefreshVoiceLibrary(arg1:main.WorkerSession):Promise<Array<main.VoiceProfile>>;

export function ReviewTextWithGateway(arg1:main.TextReviewRequest):Promise<main.TextReviewResult>;

export function SavePreferences(arg1:main.PreferencesRequest):Promise<main.StudioBootstrap>;

export function SaveTrimmedReferenceAudio(arg1:string):Promise<string>;

export function SelectAudioOutputDirectory():Promise<string>;

export function SelectReferenceAudio():Promise<string>;

export function SelectTextDocument():Promise<string>;
