// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyEmotionWithGateway(arg1) {
  return window['go']['main']['App']['ApplyEmotionWithGateway'](arg1);
}

export function AutoTranscribeReference(arg1) {
  return window['go']['main']['App']['AutoTranscribeReference'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckWorker(arg1) {
  return window['go']['main']['App']['CheckWorker'](arg1);
}

export function CreateVoice(arg1) {
  return window['go']['main']['App']['CreateVoice'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteVoice(arg1, arg2) {
  return window['go']['main']['App']['DeleteVoice'](arg1, arg2);
}

export function GenerateVoice(arg1) {
  return window['go']['main']['App']['GenerateVoice'](arg1);
}

export function ImportGoogleDriveDocument(arg1) {
  return window['go']['main']['App']['ImportGoogleDriveDocument'](arg1);
}

export function ImportTextDocument(arg1) {
  return window['go']['main']['App']['ImportTextDocument'](arg1);
}

export function ListGatewayModels(arg1) {
  return window['go']['main']['App']['ListGatewayModels'](arg1);
}

export function OpenColabNotebook() {
  return window['go']['main']['App']['OpenColabNotebook']();
}

export function OpenGoogleDrive() {
  return window['go']['main']['App']['OpenGoogleDrive']();
}

export function OpenHistoryAudio(arg1) {
  return window['go']['main']['App']['OpenHistoryAudio'](arg1);
}

export function PreviewVoice(arg1) {
  return window['go']['main']['App']['PreviewVoice'](arg1);
}

export function ReadReferenceAudioSource(arg1) {
  return window['go']['main']['App']['ReadReferenceAudioSource'](arg1);
}

export function ReadVoiceReferenceAudio(arg1) {
  return window['go']['main']['App']['ReadVoiceReferenceAudio'](arg1);
}

export function RefreshVoiceLibrary(arg1) {
  return window['go']['main']['App']['RefreshVoiceLibrary'](arg1);
}

export function ReviewTextWithGateway(arg1) {
  return window['go']['main']['App']['ReviewTextWithGateway'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SaveTrimmedReferenceAudio(arg1) {
  return window['go']['main']['App']['SaveTrimmedReferenceAudio'](arg1);
}

export function SelectAudioOutputDirectory() {
  return window['go']['main']['App']['SelectAudioOutputDirectory']();
}

export function SelectReferenceAudio() {
  return window['go']['main']['App']['SelectReferenceAudio']();
}

export function SelectTextDocument() {
  return window['go']['main']['App']['SelectTextDocument']();
}
